server:
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: ${SHOW_SQL_FORMAT:false}
    properties:
      hibernate:
        format_sql: ${SHOW_SQL_FORMAT:false}
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      # swagger não funciona sem.
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    baseline-on-migrate: true


cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}


