version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: expense-register
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: expense-register
    ports:
      - "5432:5432"
    volumes:
      - C:\Projetos\Estudos\Volumes\expenseregister:/var/lib/postgresql/data